# Generated by Django 5.1.7 on 2025-03-24 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chef_ai', '0002_alter_ingredients_ingredient_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredients',
            new_name='Ingredient',
        ),
    ]
