# Generated by Django 5.1.7 on 2025-03-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_ai', '0004_alter_ingredient_ingredient_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_name',
            field=models.CharField(max_length=75, unique=True),
        ),
    ]
