# Generated by Django 5.1.7 on 2025-04-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_ai', '0006_userhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhistory',
            name='title',
            field=models.CharField(default='Untitled Recipe', max_length=255),
        ),
    ]
